# Generated by Django 2.2.4 on 2020-08-08 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app10', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
