# Generated by Django 2.2.4 on 2020-07-06 07:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('pno', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30, unique=True)),
                ('quantity', models.IntegerField()),
                ('price', models.FloatField()),
                ('mfr_date', models.DateField(default=datetime.datetime(2020, 7, 6, 13, 1, 11, 209563))),
                ('exp_date', models.DateField(default=datetime.datetime(2020, 7, 6, 13, 1, 11, 209563))),
            ],
        ),
    ]
