# Generated by Django 2.2.4 on 2020-07-03 06:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app5', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='exp_date',
            field=models.DateField(default=datetime.datetime(2020, 7, 3, 12, 5, 42, 860155)),
        ),
        migrations.AlterField(
            model_name='product',
            name='mfr_date',
            field=models.DateField(default=datetime.datetime(2020, 7, 3, 12, 5, 42, 859153)),
        ),
    ]
