# Generated by Django 2.2.4 on 2020-08-09 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProviderDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('gender', models.CharField(max_length=6)),
                ('contact', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('address', models.TextField()),
                ('uaername', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
                ('photo', models.ImageField(upload_to='provider_photo/')),
            ],
        ),
    ]
