# Generated by Django 2.2.4 on 2020-08-09 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='providerdetails',
            name='id',
        ),
        migrations.RemoveField(
            model_name='providerdetails',
            name='uaername',
        ),
        migrations.AlterField(
            model_name='providerdetails',
            name='contact',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='providerdetails',
            name='email',
            field=models.EmailField(max_length=254, primary_key=True, serialize=False, unique=True),
        ),
    ]
